### PR TITLE
Add DMA support for SAMD21 and SAMD51 chips

### PR DESCRIPTION
**Pull request by ladyada**
This doubles the read speed. We don't use it for write (something is not working with it yet) but this is a good start!

### CODE REVIEW

**Comment by greiman** [comment]
SdFat version 1 is frozen and will only have bug fixes.  

I will look at adding it to Version 2 which is here [SdFat-beta](https://github.com/greiman/SdFat-beta).

I am still modifying the structure of drivers since I am currently adding support for USB devices, hard drives and keys.

**Comment by ladyada** [comment]
ok - you can close this PR, i guess we can have people manually download our fork for now. or should we move over to using v2?

**Comment by ladyada** [comment]
tagging @PaintYourDragon FYI

**Comment by greiman** [comment]
I really don't want to maintain special SPI drivers in the future.  They tend to conflict with future developments of the system driver.

I have managed to get several board developers to enhance their SPI system driver and I just wrap it to fit the SdFat SPI API.

I suggest you provide DMA for the SAMD system driver.

The best API is` void transfer(const void* txbuf, void* rxbuf, size_t count)`.   Where txbuf or rxbuf may be nullptr.

I have used the standard Arduino `void transfer(void* buf, size_t count) `.  This form requires a memset for read or a memcpy to a local buffer for write which is still fast.

You must send zero or 0XFF during receive.
```
  memset(buf, 0XFF, n);
  m_spi->transfer(buf, n);
```
Here is a case that required 4-byte aligned write.
```
  uint32_t tmp[128];
  if (0 < n && n <= 512) {
    memcpy(tmp, buf, n);
    m_spi->transfer(tmp, n);
  }
```

**Comment by ladyada** [comment]
` void transfer(const void* txbuf, void* rxbuf, size_t count)` it is!

**Comment by greiman** [comment]
I hope you can have it added to the system driver for Arduino.

**Comment by ladyada** [comment]
yeah it would be in the SPIClass

**Comment by greiman** [comment]
The SD standard specifies two FATs!

**Comment by ladyada** [comment]
hiya, yeah for SD 2 is required...but QSPI memory is very small, and we now support that as well, so we're allowing 1 FAT for lil chips :) we'll keep hacking on our fork - there's enough changes we will be posting it to the library manager under "SdFat (Adafruit Fork)" is that OK?

**Comment by greiman** [comment]
you can do what ever you want.  

I will soon post SdFat 2.0 which is currently in [beta](https://github.com/greiman/SdFat-beta).  This is a major rewrite of SdFat. So I won't support V 1.0

**Comment by ladyada** [comment]
totally understand. about not supporting v1.0 - we'll look at 2.0

FAT isnt the right FS for small chips, its true :) there's no other simple way to have the chip appear as a mass storage device, the convenience-of-which overrides the wear leveling concerns. having a 2-8MB QSPI chip appear as a disk drive for drag and drop file management is soooo useful!

**Pull request closed without merging**
