### PR TITLE
Update SdSpiSTM32F1.cpp

### PR DESCRIPTION
**Pull request by stevstrong**
- use buffered non-DMA read transfer instead of multiple single transfers

### CODE REVIEW

**Comment by greiman** [comment]
I changed to single byte transfers since multi-byte transfers failed on some boards.

**Comment by stevstrong** [comment]
The Arduino_STM32 core and the similar ones have implemented the multi-byte transfer for F1, so each board using these cores should support this mode.

**Comment by greiman** [comment]
Has it been fixed?  I originally had multi-byte read and it worked on some F1 boards and failed on others.

Guess I will enable it again.  I didn't test it so let me know if there is a problem.

**Comment by greiman** [comment]
I checked and there has been a major change since the 1/15/2017 version that was failing.

**Comment by stevstrong** [comment]
Yeah, that old version was a temporary version, it was buggy, clearly it did not write anything to the port, just read, that is why it did not work.
The new version was tested and it should work.

**Pull request closed without merging**
