### PR TITLE
Add support for GPT partition tables

### PR DESCRIPTION
**Pull request by PetteriAimonen**
Especially Mac OS X Disk Utility formats SD cards as GPT partition table by default.
This pull request adds support in SdFat to access these SD cards also.

### CODE REVIEW

**Comment by greiman** [comment]
I probably won't add this since I have a policy of only supporting the official SD Association  format.

**Comment by PetteriAimonen** [comment]
Hmm, ok. The newest SDUC format does use GPT officially also, but I guess there are other things that prevent it from working currently.

**Comment by greiman** [comment]
The official format specifies a single layout for a given size card and manufactures arrange flash, buffing and algorithms according to this layout.

Buffering for FAT areas is different form data areas.  Management of flash record units and management is based on this layout.

**Comment by greiman** [comment]
>  I guess even the existing support for partitions 2-4 goes beyond the SD card official spec.

SD cards have a single partition and almost every field from Medium Identifier to Cluster Size is specified for a given SD size.

The first 32,768 sectors must only contain the Master Boot Record and Partition Table.  This is for reliability so this area will never need rewrite for wear leveling.  So most of the first 16 MiB is not used.

The exFAT Up-case Table is totally specified.

**Pull request closed without merging**
