### PR TITLE
Add support for STM32F4

### PR DESCRIPTION
**Pull request by stevstrong**
As the title says, this will add support for STM32F4 family devices, tested an black F4 board, see:
- http://www.stm32duino.com/viewtopic.php?f=39&t=2215
- http://www.stm32duino.com/viewtopic.php?f=39&t=1976

The PR includes small changes needed to bring the files in line with your master.

### CODE REVIEW

**Comment by greiman** [comment]
I will look at it.  As you may know, SdFat is frozen except for minor changes.

I am doing a new library, SdFs, which supports exFAT in addition to FAT12/FAT16/FAT32.  I want the new driver architecture to support USB hard drives and flash keys.

**Comment by greiman** [comment]
The F4 stuff is unstable,  at least with a Discovery F407.  I can't get the bench program to run to completion.

I made a single SdSpiSTM32.cpp file for both F1 and F4 so the same code would run on F1 and F4.

I spent a lot of time trying DMA and non DMA with the F4. 

I put the code on GitHub so please try it on F4.  It is using DMA on F4.

Here is another strange thing about F4.
```
void setup() {
}
void loop() {
  yield();
}
```
Gives this warning.  If yield is called, programs may fail but not always.

> sketch\sketch_sep19a.ino.cpp.o: In function `loop()':
> 
> C:\Users\bill\Documents\ArduinoSdFs\sketch_sep19a/sketch_sep19a.ino:4: warning: undefined reference to `yield'
> 
> Sketch uses 19192 bytes (1%) of program storage space. Maximum is 1048576 bytes.
> Global variables use 11920 bytes (9%) of dynamic memory, leaving 119152 bytes for local variables. Maximum is 131072 bytes.

When I comment out yield calls F4 seems to work better but I can't do that in general since some systems need a yield call in long wait loops for Wi-Fi.

**Comment by stevstrong** [comment]
Bill, sorry, I forgot to mention that F4 currently only works with [my repo](https://github.com/stevstrong/Arduino_STM32), which is a further developed fork of the Roger's repo (at least for F4). I would recommend to use this for testing F4 stuff.

However, it still may happen that it will give you some errosr/warnings if you use the disco F4, because all my development was directed to and tested on the [generic black F4 board](http://wiki.stm32duino.com/index.php?title=STM32F407) as I don't own any disco F4 board.

Indeed, it seems that yield(), although defined in Arduino.h, was missing from any C file. 
I just [added it to my repo](https://github.com/stevstrong/Arduino_STM32/commit/405294948f0fdd1d12c751fbb24a45e3851fc235), so it should work now.

**Comment by greiman** [comment]
> Bill, sorry, I forgot to mention that F4 currently only works with my repo, which is a further developed fork of the Roger's repo (at least for F4). I would recommend to use this for testing F4 stuff.

I don't use STM32durino since it does not support interesting STM32 boards so I will close this.

I am now moving from STM32F7 to STM32H7.
  
A STM32F407 delivers 210 DMIPS/566 CoreMark, an STM32H7 does 856 DMIPS/2020 CoreMark.

STM32H7 can do a context switch in 1/3 microsecond with ChibiOS/RT.

**Pull request closed without merging**
