### PR TITLE
Allow external function manipulate CS

### PR DESCRIPTION
**Pull request by kostuch**
Hi,
I have a project where SPI devices have CS lines connected to I2C expander (PCF8574/PCF8575).
It's because lack of free I/O lines in esp8266 chip.
In this case use digitalWrite() to manipulate CS is not possible.
This patch allow define in application a function to manipulate CS.
Of course I2C is one of many possibilities. Defined function can use any other protocol or algorithm.
So far I tested it with USE_STANDARD_SPI_LIBRARY 0 and 1.
Simple example sketch included.

### CODE REVIEW

**Comment by greiman** [comment]
I am not adding features to SdFat V1.

In [SdFat V2](https://github.com/greiman/SdFat-beta) I plan to isolate Arduino functions to allow SdFat to be used in other systems.  The internals of V2 are still changing.

I need to allow for systems with SPI controllers that handle chip select in hardware without action by the application.

I also am using a single class for both SPI and SDIO controllers. 

I will keep this request in mind.

**Comment by kostuch** [comment]
Thank you for your answer.
I look forward to see similar functionality in SdFat ver 2.
Appreciate your work.

**Comment by greiman** [comment]
I will soon post a solution for external CS functions in SdFat V2.  Also a major reorganization of SPI drivers that allows for external SPI drivers which don't depend on Arduino SPI features.

The solution will allow three modes for manipulating CS.  Here is the SdFatConfig.h section.
```
/**
 * SD_CHIP_SELECT_MODE defines how the functions
 * void sdCsInit(SdCsPin_t pin) {pinMode(pin, OUTPUT);}
 * and
 * void sdCsWrite(SdCsPin_t pin, bool level) {digitalWrite(pin, level);}
 * are defined.
 *
 * 0 - Internal definition is a strong symbol and can't be replaced.
 *
 * 1 - Internal definition is a weak symbol and can be replaced.
 *
 * 2 - No internal definition and must be defined in the application.
 */
#define SD_CHIP_SELECT_MODE 0
```
So if you choose mode 1, you have the option of adding your own version of these two functions and the linker will replace the weak versions.

If you choose mode 2, no internal version will be provided.  This version will work with RTOS systems that don't have digitalWrite() and pinMode().

**Comment by greiman** [comment]
I posted a version of [SdFat-beta](https://github.com/greiman/SdFat-beta) with the ability to add custom functions for a port expander connected to SD chip select.

Just edit SdFatConfig.h and set SD_CHIP_SELECT_MODE to one or two.

Provide the functions `void sdCsInit(SdCsPin_t pin)` and `void sdCsWrite(SdCsPin_t pin, bool level)` for the port expander in your sketch.

If you try it, let me know if it works.

**Comment by kostuch** [comment]
Hi,
I tried to compile simple sketch (based on opennext example). But I have few questions:
I'm not sure what for is first parameter in sdCsWrite function. Is it just dummy one?
Function sdCsInit should set CS to high at the beginning or can be empty?
If I do not define SD_CS_PIN, then following define is invalid
#define SD_CONFIG SdSpiConfig(SD_CS_PIN, SHARED_SPI)
Should I set it to any fake value?

Anyway I failed compile sketch. See below
```

#include "SdFat.h"
#include <Wire.h>
#include <pcf8574_esp.h>

PCF857x				pcf8575(0x20, &Wire, true);							// Expander

void sdCsInit(SdCsPin_t pin)
{}

void sdCsWrite(SdCsPin_t pin, bool level)
{
	if (level) pcf8575.write(2, HIGH);
	else pcf8575.write(2, LOW);
}
// SD_FAT_TYPE = 0 for SdFat/File as defined in SdFatConfig.h,
// 1 for FAT16/FAT32, 2 for exFAT, 3 for FAT16/FAT32 and exFAT.
#define SD_CS_PIN 0 // Fake value???
#define SD_CONFIG SdSpiConfig(SD_CS_PIN, SHARED_SPI)

SdFat sd;
File dir;
File file;
//------------------------------------------------------------------------------
// Store error strings in flash to save RAM.
#define error(s) sd.errorHalt(&Serial, F(s))
//------------------------------------------------------------------------------
void setup()
{
	Serial.begin(115200);

	while (!Serial)	SysCall::yield();

	Wire.setClock((uint32_t)400000);											// I2C clock
	Wire.begin();																// I2C
	pcf8575.begin();															// PCF8574

	if (!sd.begin(SD_CONFIG))	sd.initErrorHalt(&Serial);

	if (!dir.open("/"))	error("dir.open failed");

	while (file.openNext(&dir, O_RDONLY))
	{
		file.printFileSize(&Serial);
		Serial.write(' ');
		file.printModifyDateTime(&Serial);
		Serial.write(' ');
		file.printName(&Serial);

		if (file.isDir())	Serial.write('/');

		Serial.println();
		file.close();
	}

	if (dir.getError())	Serial.println("openNext failed");
	else Serial.println("Done!");
}
void loop() {}

```

```
Dependency Graph
|-- <PCF8574_ESP> 1.0.3
|   |-- <Wire> 1.0
|-- <Wire> 1.0
|-- <src>
|   |-- <SPI> 1.0
Building in release mode
Compiling .pio\build\esp12e\src\main.cpp.o
Linking .pio\build\esp12e\firmware.elf
c:/users/mp/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: .pio\build\esp12e\src\main.cpp.o:(.text._ZN10StreamFileI7FatFilejE5writeEPKhj[StreamFile<FatFile, unsigned int>::write(unsigned char const*, unsigned int)]+0x0): undefined reference to `FatFile::write(void const*, unsigned int)'
c:/users/mp/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: .pio\build\esp12e\src\main.cpp.o: in function `StreamFile<FatFile, unsigned int>::write(unsigned char const*, unsigned int)':
main.cpp:(.text._ZN10StreamFileI7FatFilejE5writeEPKhj[StreamFile<FatFile, unsigned int>::write(unsigned char const*, unsigned int)]+0xc): undefined reference to `FatFile::write(void const*, unsigned int)'

```
...and lot more compile errors

**Comment by greiman** [comment]
The pin parameter in sdCsInit and sdCsWrite is not a dummy parameter.  Many users have more than one SD card.   In some systems a user may use GPIO functions other than digitalWrite and pinMode.

If you only use one SD card you can ignore the value of the first parameter.

The compile error you provided don't provide much info the actual cause of the failure.

I don't have your port expander so I ran the following on an Adafruit Feather HUZZAH ESP8266.

 I tried both one and two for SD_CHIP_SELECT_MODE.  SD chip select is connected to pin 15 which is SS.


```
#include "SdFat.h"
#define CS_PIN SS
void sdCsInit(SdCsPin_t pin) {
  (void)pin; 
  pinMode(CS_PIN, OUTPUT);
}
void sdCsWrite(SdCsPin_t pin, bool level) {
  (void)pin; 
  digitalWrite(CS_PIN, level);
}

// SD_FAT_TYPE = 0 for SdFat/File as defined in SdFatConfig.h,
// 1 for FAT16/FAT32, 2 for exFAT, 3 for FAT16/FAT32 and exFAT.

#define SD_CS_PIN 0 // Fake value???
#define SD_CONFIG SdSpiConfig(SD_CS_PIN, SHARED_SPI)

SdFat sd;
File dir;
File file;
//------------------------------------------------------------------------------
// Store error strings in flash to save RAM.
#define error(s) sd.errorHalt(&Serial, F(s))
//------------------------------------------------------------------------------
void setup()
{
  Serial.begin(115200);

  while (!Serial) SysCall::yield();

  if (!sd.begin(SD_CONFIG)) sd.initErrorHalt(&Serial);

  if (!dir.open("/")) error("dir.open failed");

  while (file.openNext(&dir, O_RDONLY))
  {
    file.printFileSize(&Serial);
    Serial.write(' ');
    file.printModifyDateTime(&Serial);
    Serial.write(' ');
    file.printName(&Serial);

    if (file.isDir()) Serial.write('/');

    Serial.println();
    file.close();
  }

  if (dir.getError()) Serial.println("openNext failed");
  else Serial.println("Done!");
}
void loop() {}
```
This is the output:
```
        0 2019-11-18 07:02 System Volume Information/
         0 2000-01-01 01:00 Dir1/
   5000000                  bench.dat
         0                  Dir2/
   8388608                  TeensyDemo.bin
Done!
```

**Comment by greiman** [comment]
I replaced sdCsInit with this, (void) cast to stop warnings.
`void sdCsInit(SdCsPin_t pin) {(void)pin;}`

And moved the pinMode to here:
```
  while (!Serial) SysCall::yield();
  pinMode(CS_PIN, OUTPUT);
  if (!sd.begin(SD_CONFIG)) sd.initErrorHalt(&Serial);
```
Still workd.

**Comment by kostuch** [comment]
OK, I managed to compile my sketch (missing lib dependency).
With SD_CHIP_SELECT_MODE set to 1 or 2, output is:

```
begin() failed
Do not reformat the SD.
No card, wrong chip select pin, or wiring error?
SdError: 0X1,0XFF
```

The SD card and wiring is ok, as using other lib I can initialize and access files on it.
I wonder what is the sense of sequence in my case (CS connected to port expander):
```
#define SD_CS_PIN 0 // Fake value???
#define SD_CONFIG SdSpiConfig(SD_CS_PIN, SHARED_SPI)
```

It doesn't make sense to define CS pin number, as it is not connected to any MCU pad.

**Comment by greiman** [comment]
> It doesn't make sense to define CS pin number, as it is not connected to any MCU pad.

I want to be able to multiple SD cards,  allow optional replacement of the functions, use  other GPIO libraries such as with an RTOS, or allow pins to be either on an expander or regular pad.  This require a pin name/number.

Don't worry.  If your replace void sdCsInit and sdCsWrite, nothing in SdFat will use the pin number.

The only functions that use pin number are in SdSpiChipSelect.cpp.  Here are the functions.
```
#if SD_CHIP_SELECT_MODE == 0
//------------------------------------------------------------------------------
void sdCsInit(SdCsPin_t pin) {
  pinMode(pin, OUTPUT);
}
//------------------------------------------------------------------------------
void sdCsWrite(SdCsPin_t pin, bool level) {
  digitalWrite(pin, level);
}
//------------------------------------------------------------------------------
#elif SD_CHIP_SELECT_MODE == 1
__attribute__((weak))
void sdCsInit(SdCsPin_t pin) {
  pinMode(pin, OUTPUT);
}
//------------------------------------------------------------------------------
__attribute__((weak))
void sdCsWrite(SdCsPin_t pin, bool level) {
  digitalWrite(pin, level);
}
#endif  // SD_CHIP_SELECT_MODE == 0
```
My example above does not depend on the passed value.  I use zero just like your example.

**Comment by kostuch** [comment]
I understand.
But anyway it do not initialize card.
I add some debug line in functions, and error codes depend if I use shared or dedicated SPI.
What these errors indicate?

```
void sdCsInit(SdCsPin_t pin)
{
	Serial.println("Init expander line - not necessary, do nothing");
}

void sdCsWrite(SdCsPin_t pin, bool level)
{
	Serial.printf("Set CS level: %d\r\n", level);
	if (level) pcf8575.write(2, HIGH);
	else pcf8575.write(2, LOW);
}
```
In SHARED_SPI (I disabled CS lines for other SPI devices):
Init - do nothing
Set CS level: 1
Set CS level: 0
Set CS level: 1
Set CS level: 0
Set CS level: 1
begin() failed
Do not reformat the SD.
No card, wrong chip select pin, or wiring error?
SdError: 0X1,0XFF

In DEDICATED_SPI:
Init - do nothing
Set CS level: 1
begin() failed
Do not reformat the SD.
SdError: 0X29,0X0

**Comment by greiman** [comment]
The printed Chip Select level looks good for SHARED_SPI.  I suspect the value on the SD does not match the printed value.

DEDICATED_SPI fails because you have ENABLE_DEDICATED_SPI set to zero in SdFatConfig.h

Here is the code in SdSpiCard.cpp
```
#if ENABLE_DEDICATED_SPI
  m_sharedSpi = !(spiConfig.options & DEDICATED_SPI);
  m_spiActive = false;
  m_curState = IDLE_STATE;
#else  // ENABLE_DEDICATED_SPI
  if (spiConfig.options & DEDICATED_SPI) {
    error(SD_CARD_ERROR_INVALID_CARD_CONFIG);  <<-------Fails here
    goto fail;
  }
#endif  // ENABLE_DEDICATED_SPI
```

**Comment by kostuch** [comment]
Finally I managed to init SDcard. My fault...
So I confirm, that 2.0.0-beta.7 code works fine with CS connected to expander.
Is the current API already stable, or is it subject to change during this beta stage?

**Comment by greiman** [comment]
I have tested the external chip select API with many boards and IDEs so unless some serious problem occurs, it will not change.

**Comment by greiman** [comment]
feature added

**Pull request closed without merging**
